---
- hosts: all
  become: true
  gather_facts: no

  tasks:
  
  - name: Run the equivalent of "apt-get update" as a separate step
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 3600 #no need to check if its already worked in 3600
      
  - name: Update all packages to their latest version
    ansible.builtin.apt:
      name: "*"
      state: latest

  - name: Remove dependencies that are no longer required.
    ansible.builtin.apt:
      autoremove: yes
      
...